version: '3'
services:
    app:
        container_name: mri_sarcoma_ai
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./outputs/:/opt/project/outputs/
        environment:
            - AUTORAD_RESULT_DIR=./outputs
            - HYDRA_FULL_ERROR=1
        tty: true
        stdin_open: true
        ports:
            - 8000:8000
        mem_limit: 8000m
