version: '3'
services:
    app: &default
        container_name: mri_sarcoma_ai
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/opt/project/
        environment:
            - AUTORAD_RESULT_DIR=./outputs
            - HYDRA_FULL_ERROR=1
        tty: true
        stdin_open: true
        ports:
            - 8000:8000
        mem_limit: 8000m

    jupyter:
        <<: *default
        container_name: mri_sarcoma_ai_notebook
        ports:
            - 8888:8888
        command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser