version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        <<: &default
            container_name: mri_sarcoma_ai
            image: mri_sarcoma_ai
            volumes:
                - ./:/opt/project/
            environment:
                - AUTORAD_RESULT_DIR=./outputs
                - HYDRA_FULL_ERROR=1
            tty: true
            stdin_open: true
            ports:
                - 8000:8000
            mem_limit: 8000m
            shm_size: 6gb
            deploy:
              resources:
                reservations:
                  devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]

    jupyter:
        <<: *default
        container_name: mri_sarcoma_ai_notebook
        ports:
            - 8888:8888
        command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser