# @package _global_

pipeline:
  _target_: src.pipeline.full_ml_cycle

# ovr doesn't seem to work
multi_class: raise
name: ???
labels: Null
existing_processed_data_dir: Null

feature_dataset:
  data_dir: ???
  image_stems: [image]
  mask_stem: mask
  label_csv_path: ???
  target_column: Grade
  extraction_params: ./conf/radiomic_params/mr_default.yaml
  n_jobs: ${n_cpu}
  label_csv_encoding: Null
  feature_df_merger: Null
  existing_feature_df:

split:
  existing_split:
  method: train_with_cross_validation
  split_on:
  n_splits: 5

trainer:
  metric: roc_auc
  n_jobs: ${cpu_per_task}

models:
  - Random Forest
  - SVM
  - XGBoost
  - Logistic Regression
  - KNN
  - MLP
  - DecisionTreeClassifier

preprocessing:
  use_feature_selection: True
  feature_selection_methods:
#     - anova
    - lasso
    - linear_svc
    - tree
    - {_method_: sf, direction: backward, n_jobs: 5, tol: 0.05}
    - {_method_: rfe, n_jobs: 5}
    - mrmr
    - pca
#    boruta doesn't seem to work
#    - boruta
  use_oversampling: True
  oversampling_methods:
    - SMOTE
    - ADASYN
    - BorderlineSMOTE
  autoencoder:
  encoder_colname: 'ID'

optimizer:
  n_trials: 10

bootstrap:
    iters: 100
    cpus_per_process: ${cpu_per_task}
    labels: ${labels}
    method: '.632'
    alpha: 0.95
    stratify: True

analysis:
    compare_run_id:
    image_modalities:
    feature_classes: ['shape', 'firstorder', 'glcm', 'glrlm', 'glszm', 'gldm', 'ngtdm']


