# @package _global_

pipeline:
  _target_: src.pipeline.tune_pipeline

# ovr doesn't seem to work
multi_class: raise
name: ???
labels: Null

feature_dataset:
  data_dir: ???
  image_stems: [image]
  mask_stem: mask
  label_csv_path: ???
  target_column: Grade
  extraction_params: ./conf/radiomic_params/mr_default.yaml
  n_jobs: ${n_cpu}
  label_csv_encoding: Null
  feature_df_merger: Null
  existing_feature_df:

split:
  existing_split:
  method: train_with_cross_validation
  split_on:
  n_splits: 5

models:
  - Random Forest
  - SVM
  - XGBoost

preprocessing:
  use_feature_selection: True
  feature_selection_methods:
    - anova
    - lasso
#    boruta doesn't seem to work
#    - boruta
  use_oversampling: False
  autoencoder:
  encoder_colname: 'ID'

optimizer:
  n_trials: 10

bootstrap:
    iters: 100
    num_cpu: ${cpu_per_task}
    labels: ${labels}
    method: '.632'
    alpha: 0.95
    stratify: True



