# @package preprocessing.autoencoder


_target_: src.models.autoencoder.nn_encoder.Encoder
module: src.models.autoencoder.DummyVAE
module__in_channels: 1
module__latent_dim: 64
module__hidden_dims: [8, 16, 32]
module__finish_size: 2
max_epochs: 1
batch_size: 128
verbose: 1
lr: 0.001
output_format: pandas
criterion: src.models.autoencoder.beta_vae.BetaVAELoss
criterion__kld_weight: 0.1
dataset: src.dataset.dummy_dataset.DummyDataset







