# @package preprocessing.autoencoder

_target_: sklearn.pipeline.make_pipeline
_args_:
    - _target_: src.preprocessing.SitkImageProcessor
      data_dir: ${feature_dataset.data_dir}
      image_stems: ${feature_dataset.image_stems}
      mask_stem: ${feature_dataset.mask_stem}
    - _target_: src.models.autoencoder.nn_encoder.Encoder
      module: src.models.autoencoder.DummyVAE
      module__in_channels: 5
      module__latent_dim: 64
      module__hidden_dims: [8, 16, 32]
      module__finish_size: 2
      max_epochs: 1
      batch_size: 128
      verbose: 1
      output_format: pandas
      optimizer: torch.optim.AdamW
      criterion: src.models.autoencoder.beta_vae.BetaVAELoss
      criterion__kld_weight: 0.1
      lr: 0.001
      iterator_train: src.dataset.transforming_dataloader.TransformingDataLoader
      iterator_train__num_workers: 6
      iterator_valid__num_workers: 6
      iterator_train__augment_transforms:
        _target_: torchio.Compose
        transforms:
            - _target_: torchio.RandomGamma
              log_gamma: 0.1
              label_keys: mask
      dataset: src.dataset.skorch_subject_ds.SkorchSubjectsDataset
      dataset__transform:
        _target_: torchio.Compose
        transforms:
            - _target_: torchio.Resize
              target_shape: 16
            - _target_: torchio.Mask
              masking_method: mask
              outside_value: 0
            - _target_: torchio.ZNormalization
              masking_method: mask

      callbacks:
        - _target_: skorch.callbacks.GradientNormClipping
          gradient_clip_value: 1





