# @package preprocessing.autoencoder

defaults:
    - encoder_base.yaml
    - _self_


module: src.models.FMCIBModel
module__input_channels: 5
module__weights_path: 'outputs/pretrained_models/model_weights.torch'
batch_size: 3
max_epochs: 200
verbose: 1
criterion: "torch.nn.BCEWithLogitsLoss"
optimizer__param_groups: [['trunk.*', {'lr': 0.000001}],['latent_var_head.*',{'lr':0.001}],['heads.*', {'lr': 0.001}]]

lr: 0.001
device: cuda
iterator_train__num_workers: ${cpu_per_task}
iterator_valid__num_workers: 4
iterator_train__persistent_workers: true
iterator_valid__persistent_workers: true
