# @package preprocessing.autoencoder

defaults:
    - encoder_base.yaml
    - _self_


module: src.models.FMCIBModel
module__input_channels: 5
module__output_class: 2
module__latent_var_dim: 2048
module__weights_path: 'outputs/pretrained_models/model_weights.torch'
batch_size: 5
lr: 0.0001
weighted_sampler: true
criterion__weight: 
    _target_: torch.tensor
    _args_:
        - [0.016, 0.09]
max_epochs: 200
verbose: 1
criterion: "torch.nn.BCELoss"

device: cuda
iterator_train__num_workers: ${cpu_per_task}
iterator_valid__num_workers: 4
iterator_train__persistent_workers: true
iterator_valid__persistent_workers: true
