# @package preprocessing.autoencoder

_target_: sklearn.pipeline.make_pipeline
_args_:
    - _target_: src.dataset.dl_dataset.SitkImageProcessor
      result_dir: ./outputs
      data_dir: ${feature_dataset.data_dir}
      image_stems: ${feature_dataset.image_stems}
      mask_stem: ${feature_dataset.mask_stem}
      n_jobs: ${n_cpu}
    - _target_: src.models.autoencoder.nn_encoder.Encoder
      module: vanillavae
      module__in_channels: 5
      module__latent_dim: 128
      module__hidden_dims: [32, 64, 128]
      module__finish_size: 2
      std_dim: [0,2,3,4]
      max_epochs: 10
      verbose: 0
      output_format: pandas
      optimizer: torch.optim.AdamW
      lr: 0.0002
      callbacks:
        - _target_: skorch.callbacks.EarlyStopping
          load_best: True
        - _target_: skorch.callbacks.GradientNormClipping

