# @package preprocessing.autoencoder

_target_: sklearn.pipeline.make_pipeline
_args_:
    - _target_: src.preprocessing.SitkImageProcessor
      result_dir: ./outputs
      data_dir: ${feature_dataset.data_dir}
      image_stems: ${feature_dataset.image_stems}
      mask_stem: ${feature_dataset.mask_stem}
      n_jobs: ${n_cpu}
    - _target_: src.models.autoencoder.nn_encoder.Encoder
      module: vanillavae
      module__in_channels: 5
      module__latent_dim: 128
      module__hidden_dims: [32, 64, 128]
      module__finish_size: 2
      std_dim: [0,2,3,4]
      max_epochs: 100
      verbose: 1
      output_format: pandas
      optimizer: adamw
      criterion: mssim
      criterion__in_channels: 5
      criterion__window_size: 3
      lr: 0.0001
      callbacks:
        - _target_: skorch.callbacks.EarlyStopping
          load_best: True
        - _target_: skorch.callbacks.GradientNormClipping
      transform_kwargs:
        thetaX: [-90, 90]
        thetaY: [-90, 90]
        thetaZ: [-90, 90]
        tx: [-1, 1]
        ty: [-1, 1]
        tz: [-1, 1]
        scale: [1, 1]
        n: 10


